title: Sri Bagus Noegroho
logo: /assets/img/1680159813597-modified.png
description: Highly analytical Bachelor of Engineering graduate with a strong foundation in the energy sector, data analysis, and sustainability. Specialized in geothermal exploration and data analytics during my studies. Skilled in GHG inventory, data processing, modelling, visualization/dashboard creation and interpretation through hands-on projects and certifications. Committed to driving sustainable and just transition through data-driven approaches.
#show_downloads: true
theme: jekyll-theme-minimal
